---
title: "Models"
author: "Marcos Mariscal"
date: "23/5/2021"
output: html_document
---
```{r setup, include=FALSE}

# Getting project directory 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
proydir <- rprojroot::find_rstudio_root_file()

```

---
# Calling R libraries
---

```{r call_libraries, include=FALSE}

# Calling R libraries
library(tidyverse)
library(keras)
library(mlbench) 
library(dplyr)
library(magrittr)
library(neuralnet)
library(tensorflow)
```

---
## Enviroment variables definition
---

```{r envdefs, include=FALSE}
#Environment directories vars
airfilepath="./Data/Air_Quality/"
pngpath="./png/"
datapath="./Data/"

# Defining file names variables to load the data
file_TotRespData = "TotRespData.Rdata"

```



```{r Load_TotAgg, echo=FALSE}
# Read AQI Visits
load(file = paste(datapath,file_TotRespData, sep=""))
TotRespData

```

Getting only numeric Features for Respiratory ilnesses

```{r numeric}

NumDataResp <- TotRespData[,8:26]

```

---
# Normalization the Data
---
Z-score normalization, consists of subtracting the mean and divide by the standard deviation
We normalize the data to bring all the variables to the same range

```{r norm}
means <- colMeans(NumDataResp)
sds <- apply(NumDataResp, 2, sd)

z_NumDataResp <- scale(NumDataResp, center = means, scale = sds)

z_NumDataResp <- as_tibble(z_NumDataResp)

head(z_NumDataResp)

```

## DEEP LEARNING

```{r neural}


n <- neuralnet(AQI ~ RSP002_pneumonia+RSP005_acute_bronchitis+RSP008_chronic_pulmonary+RSP009_asthma+RSP010_aspiration_pneumonitis+RSP012_respiratory_failure+Use_mech_ventilation+RateRespVisits+TotResp+POPULATION,
               data = z_NumDataResp,
               hidden = c(10,5),
               linear.output = F,
               lifesign = 'full',
               threshold = 0.05,
               rep=1,)
```

